version: 3.1

services:
  db:
    image: postgres:latest
    tty: true
    environment:
      POSTGRES_PASSWORD: Vieh12468
      POSTGRES_DB: steam_archive
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - db

volumes:
  db_data: {}
